import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/src/lib/utils";
import Navbar from "@/src/components/Navbar";
import AppInitializer from "@/src/components/auth/AppInitializer";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SH-Supplements",
  description: "Generated by SH-Supplements",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased bg-[#F9F9F9]">
        <Toaster position="top-right" richColors closeButton />
        <AppInitializer>
          <Navbar />
          <div className="flex min-h-[calc(screen-80px)] w-full">
            <aside className="sticky top-[61px] h-[calc(100vh-61px)] hidden md:block z-40">
            </aside>
            <main className="flex-1 p-6 overflow-y-auto">{children}</main>
          </div>
        </AppInitializer>
      </body>
    </html>
  );
}
